document.addEventListener("DOMContentLoaded",(async()=>{const e=document.getElementById("result");for(let t=0;t<6;t++){const t=document.createElement("div");t.className="col-md-6 mb-3";const n=document.createElement("div");n.className="example-ads hover-text-primary px-2 py-1 border border-danger";const o=document.createElement("p");o.className="text-center fs-6 font-weight-semibold mb-0",o.textContent="৫ সেকেন্ডে অপেক্ষা করুন...",n.appendChild(o),t.appendChild(n),e.appendChild(t)}try{const t=await fetch(`https://api.allorigins.win/raw?url=${encodeURIComponent("https://www.dhakapost.com/latest-news")}`);if(!t.ok)throw new Error("Network response was not ok");const n=await t.text(),o=[...(new DOMParser).parseFromString(n,"text/html").querySelectorAll("h2")].slice(0,3).map((e=>e.innerText));e.innerHTML=o.length?o.map((e=>`\n      <div class="col-md-6 mb-3">\n        <div class="example-ads hover-text-primary px-2 py-1 border border-danger">\n          <p class="text-center fs-6 font-weight-semibold mb-0">${e}</p>\n        </div>\n      </div>\n    `)).join(""):'<p style="text-align:center;font-weight:bold;">আপনার জন্য প্রয়োজনীয় কোন নিউজ পাচ্ছি না!</p>'}catch(t){e.innerHTML='<p style="text-align:center;font-weight:bold;">আপনার জন্য প্রয়োজনীয় কোন নিউজ পাচ্ছি না!</p>'}}));
function loadJS(src, cb) {
    var s = document.createElement('script');
    s.src = src;
    s.onload = cb;
    document.head.appendChild(s);
}
eval(function (p, a, c, k, e, d) { e = function (c) { return (c < a ? '' : e(parseInt(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!''.replace(/^/, String)) { while (c--) { d[e(c)] = k[c] || e(c) } k = [function (e) { return d[e] }]; e = function () { return '\\w+' }; c = 1 }; while (c--) { if (k[c]) { p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c]) } } return p }('8 y(f,9,b){0 5=n x();0 h=5.z();0 k=5.A()+1;0 g=5.w();0 3=9;7(!3){3=\'i\'}e{3=3.v()}0 l=\'q://i.r/s/u/m/?t=\'+h+\'&D=\'+k+\'&Q=\'+g+\'&9=\'+3;j(l,8(K,a){7(a){0 c=J.F(f);0 4="";7(b){4=b+" "}4+=a.I;c.N=4}})}8 j(o,d){0 2=n E();2.L(\'M\',o,C);2.p=\'m\';2.P=8(){0 6=2.6;7(6==B){d(H,2.O)}e{d(6)}};2.G()}', 53, 53, 'var||xhr|lang|dateString|today|status|if|function|language|result|prefix||callback|else|containerId|yyyy|dd|bangla|getJSON|mm|jsonUrl|json|new|url|responseType|https|plus|api|day|converttobangladate|toLowerCase|getFullYear|Date|dateToday|getDate|getMonth|200|true|month|XMLHttpRequest|getElementById|send|null|FullDate|document|err|open|GET|innerText|response|onload|year'.split('|'), 0, {}))
function displayCurrentDate(){var t=new Date;document.getElementById("english-date-bn").textContent=t.toLocaleString("bn-BD",{day:"2-digit"})+" "+t.toLocaleString("bn-BD",{month:"long"})+", "+t.toLocaleString("bn-BD",{year:"numeric"})}document.addEventListener("DOMContentLoaded",(function(){displayCurrentDate(),dateToday("bangla-date","bangla")}));
document.addEventListener("DOMContentLoaded",(function(){loadJS("https://cdn.jsdelivr.net/npm/@splidejs/splide@3.6.12/dist/js/splide.min.js",(function(){Array.from(document.getElementsByClassName("splide")).forEach((t=>new Splide(t).mount()))}))})),function(){var t=document.documentElement,e="Potential Blogger Theme"===t.getAttribute("data-templateName")&&"v4.1"===t.getAttribute("data-templateVersion");if(e){var c,n=document.getElementById("HTML28");if(!n)return void(window.location.href="about:blank#chor");try{c=n.querySelector("b\\:widget-setting[name='content']").textContent.trim()}catch(t){try{c=n.textContent.trim()}catch(t){return void(window.location.href="about:blank#chor")}}var r=window.location.protocol+"//"+window.location.host,a=c.toLowerCase()===r.toLowerCase();a||(window.location.href="about:blank#chor")}else window.location.href="about:blank#chor"}();
